language: objective-c
osx_image: xcode10.2
script:
  - fastlane scan Typhoon.xcodeproj --scheme Typhoon-iOSTests
  - fastlane scan Typhoon.xcodeproj --scheme Typhoon-OSXTests
  - fastlane scan Typhoon.xcodeproj --scheme TyphoonFrameworkSwiftExample

after_success:
  - bash <(curl -s https://codecov.io/bash)


